# DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 5
  labels:
    run: simple-spring-boot-k8s-app
  name: simple-spring-boot-k8s-app
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: simple-spring-boot-k8s-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: simple-spring-boot-k8s-app
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: '-XX:MaxRAM=450m'
        image: #IMAGE_NAME
        imagePullPolicy: Always
        name: simple-spring-boot-k8s-app
        ports:
        - containerPort: 9197
          protocol: TCP
        resources:
          limits:
            memory: 450Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60

---

# SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: simple-spring-boot-k8s-app
  name: simple-spring-boot-k8s-app
  namespace: default
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: simple-spring-boot-k8s-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}

